export const POLKADOT_NETWORK_NAME = "Polkadot Asset Hub";
export const SS58_FORMAT = 0;
export const WALLET_KEY = "relay-wallet";
export const WALLET_SEED_KEY = "relay-wallet-seed";
export const ENCRYPTED_WALLET_KEY = "relay-encrypted";
export const IS_ENCRYPTED_KEY = "is-encrypted";
export const USER_KEY = "relay-user";
export const IS_BACKED_UP_KEY = "is-relay-backed-up";
export const NETWORK_MODE_KEY = "relay-network-mode";
